# -*- coding: utf-8 -*-
"""load_googlesheets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uDUHrc4EQSoOXGF_874bB7OmbVYUxHRh
"""

# Bentuk Google Sheets
from google.oauth2 import service_account
from googleapiclient.discovery import build
import logging
import pandas as pd

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

ID_SPREADSHEET = "1m6PnN4NuyFY3rin66qBQZ2n02-XabaUIprxjXszs34c"
NAME_SHEET = "Sheet1"

def saved_to_google_sheets(df: pd.DataFrame):
  try:
    credential = service_account.Credentials.from_service_account_file(
        "google-sheets-api.json", scopes=["https://www.googleapis.com/auth/spreadsheets"]
    )

    service = build("sheets", "v4", credentials=credential)
    sheet = service.spreadsheets()

    # Mengonversi Kolom Timestamp menjadi String
    df_for_sheets = df.copy()
    if "Timestamp" in df_for_sheets.columns:
      df_for_sheets["Timestamp"] = df_for_sheets["Timestamp"].astype(str)

    values = [df_for_sheets.columns.values.tolist()] + df_for_sheets.values.tolist()

    request = sheet.values().update(
        spreadsheetId = ID_SPREADSHEET,
        range = NAME_SHEET,
        valueInputOption = "RAW",
        body = {"values": values}
    )
    response = request.execute()
    logger.info(f"Data berhasil disimpan ke Google Sheets: {response}")
    return response

  except Exception as e:
    logger.error(f"Terjadi kesalahan saat menyimpan data ke Google Sheets: {e}")
    return None