# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14CdjGNWNoRhQg4ApX_Ac1JkavOMdJWuB
"""

import pandas as pd
from utils.extract_data.extract import scrape_main
from utils.transform_data.transform import transform_data
from utils.load_data.load_csv import saved_to_csv
from utils.load_data.load_googlesheets import saved_to_google_sheets

def main():
    try:
        print("Memulai Proses Keseluruhan ETL\n")

        print("Menjalankan Extract")
        raw_data = scrape_main()
        if not raw_data:
            raise ValueError("Extract gagal dilakukan")

        print("\nMenjalankan Transformasi")
        transformed_df = transform_data(raw_data)
        if transformed_df.empty:
            raise ValueError("Transformasi gagal dilakukan")

        print("\nMenyimpan Data")
        saved_to_csv(transformed_df, "products.csv")
        saved_to_google_sheets(transformed_df)

        print(f"Jumlah data setelah melakukan ETL: {len(transformed_df)}")

        print("\nProses ETL telah selesai dilakukan")

    except Exception as e:
        print(f"\nTerdapat Error dalam proses melakukan ETL: {e}")

if __name__ == "__main__":
    main()