# -*- coding: utf-8 -*-
"""check tipe & invalid data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oAcbFz725AVkoew92tuKePxorpKz6vAd
"""

import pandas as pd

df = pd.read_csv("products.csv")

# Menampilkan Data
print(df.head())

# Menampilkan Tipe Data setiap Elemen
df.info()

# Memeriksa Missing Values
print("\nMissing values:")
print(df.isnull().sum())

# Memeriksa Duplikasi
print(f"\nJumlah baris duplikasi: {df.duplicated().sum()}")

# Memeriksa Nilai Unik Kolom "Size" dan "Gender"
print("\nNilai unik pada Kolom Size:")
print(df["Size"].unique())

print("\nNilai unik pada Kolom Gender:")
print(df["Gender"].unique())

# Memeriksa Invalid Data kolom "Title", "Rating", dan "Price"
dirty_patterns = {
    "Title": ["Unknown Product"],
    "Rating": ["Invalid Rating / 5", "Not Rated"],
    "Price": ["Price Unavailable", None]
}

def dirty_data_check(df, dirty_patterns):
    rows_dirty = []

    for column, patterns in dirty_patterns.items():
        if column in df.columns:
            for pattern in patterns:
                if pattern is None:
                    matches = df[df[column].isna()]
                else:
                    matches = df[df[column] == pattern]

                if not matches.empty:
                    rows_dirty.append(matches)

    return pd.concat(rows_dirty) if rows_dirty else pd.DataFrame()

data_dirty = dirty_data_check(df, dirty_patterns)

if not data_dirty.empty:
    print("Ditemukan data kotor pada dataset products:")
    print(data_dirty)
else:
    print("Tidak ditemukan data kotor pada dataset products")