# -*- coding: utf-8 -*-
"""load_csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M4EqHJK6H9OumYSZYi7Sw50uv3FTht52
"""

# Bentuk CSV
import pandas as pd

def saved_to_csv(df, filename="products.csv"):
    try:
        df.to_csv(filename, index=False)
        print(f"Data berhasil disimpan ke {filename}")
    except Exception as e:
        print(f"Error ketika menyimpan data ke CSV: {e}")
        raise